### ISSUE TITLE
[BUG]"Random crop padding percent" (under subsets) resets to 0.05 after saving it with 0.00 value in GUI and realoading toml

### ISSUE THREAD

**Issue by neojam** [67372a/LoRA_Easy_Training_Scripts#32]
**Describe the bug**
"Random crop padding percent" (under subsets) resets to 0.05 after saving it with 0.00 value in GUI and realoading toml

**To Reproduce**
1. Go to "subset args"
2. Set "Random crop padding percent" to 0.00 (its default value) in your dataset options
3. Save config to a toml file
4. load the toml file 
5. "Random crop padding percent" (under subsets) is now set to 0.05

**Expected behavior**
1.
"random_crop_padding_percent = 0.00" should be saved to toml file if the value was set to 0.00 in the GUI.
(Currently "random_crop_padding_percent" is missing in the toml file, if it was set to 0.00 in the gui.)

2.
If "random_crop_padding_percent" is missing in the toml file, "Random crop padding percent" should be set to 0.00 after loading the toml file.

**Comment by neojam** [comment]
Displays now correctly in GUI as "0.0", but the console shows shows "0.05" for  when you start training:

```
                                 num_repeats: 3
                                 shuffle_caption: True
                                 shuffle_caption_sigma: 0
                                 keep_tokens: 1
                                 keep_tokens_separator:
                                 caption_separator: ,
                                 secondary_separator: None
                                 enable_wildcard: False
                                 caption_dropout_rate: 0.0
                                 caption_dropout_every_n_epochs: 0
                                 caption_tag_dropout_rate: 0.0
                                 caption_prefix: None
                                 caption_suffix: None
                                 color_aug: False
                                 flip_aug: False
                                 face_crop_aug_range: None
                                 random_crop: False
                                 random_crop_padding_percent: 0.05
                                 token_warmup_min: 1
                                 token_warmup_step: 0
                                 alpha_mask: False
                                 custom_attributes: {}
                                 is_reg: False
                                 is_val: False
                                 class_tokens: None
                                 caption_extension: .txt
```
